#!/usr/bin/bash
clustalw -INFILE=cluster7size18.txt -TYPE=protein 
clustalw -INFILE=cluster4size23.txt -TYPE=protein 
clustalw -INFILE=cluster63size5.txt -TYPE=protein 
clustalw -INFILE=cluster54size6.txt -TYPE=protein 
clustalw -INFILE=cluster78size5.txt -TYPE=protein 
clustalw -INFILE=cluster19size10.txt -TYPE=protein 
clustalw -INFILE=cluster59size6.txt -TYPE=protein 
clustalw -INFILE=cluster49size7.txt -TYPE=protein 
clustalw -INFILE=cluster16size11.txt -TYPE=protein 
clustalw -INFILE=cluster41size7.txt -TYPE=protein 
clustalw -INFILE=cluster31size8.txt -TYPE=protein 
clustalw -INFILE=cluster74size5.txt -TYPE=protein 
clustalw -INFILE=cluster32size8.txt -TYPE=protein 
clustalw -INFILE=cluster81size5.txt -TYPE=protein 
clustalw -INFILE=cluster13size11.txt -TYPE=protein 
clustalw -INFILE=cluster35size7.txt -TYPE=protein 
clustalw -INFILE=cluster52size6.txt -TYPE=protein 
clustalw -INFILE=cluster15size11.txt -TYPE=protein 
clustalw -INFILE=cluster80size5.txt -TYPE=protein 
clustalw -INFILE=cluster46size7.txt -TYPE=protein 
clustalw -INFILE=cluster20size10.txt -TYPE=protein 
clustalw -INFILE=cluster6size19.txt -TYPE=protein 
clustalw -INFILE=cluster33size8.txt -TYPE=protein 
clustalw -INFILE=cluster56size6.txt -TYPE=protein 
clustalw -INFILE=cluster2size30.txt -TYPE=protein 
clustalw -INFILE=cluster70size5.txt -TYPE=protein 
clustalw -INFILE=cluster25size9.txt -TYPE=protein 
clustalw -INFILE=SECOM_config.txt -TYPE=protein 
clustalw -INFILE=cluster28size8.txt -TYPE=protein 
clustalw -INFILE=cluster47size7.txt -TYPE=protein 
clustalw -INFILE=cluster18size10.txt -TYPE=protein 
clustalw -INFILE=cluster17size10.txt -TYPE=protein 
clustalw -INFILE=cluster40size7.txt -TYPE=protein 
clustalw -INFILE=cluster62size5.txt -TYPE=protein 
clustalw -INFILE=cluster77size5.txt -TYPE=protein 
clustalw -INFILE=cluster76size5.txt -TYPE=protein 
clustalw -INFILE=cluster29size8.txt -TYPE=protein 
clustalw -INFILE=cluster44size7.txt -TYPE=protein 
clustalw -INFILE=cluster27size8.txt -TYPE=protein 
clustalw -INFILE=cluster42size7.txt -TYPE=protein 
clustalw -INFILE=cluster48size7.txt -TYPE=protein 
clustalw -INFILE=cluster50size6.txt -TYPE=protein 
clustalw -INFILE=cluster55size6.txt -TYPE=protein 
clustalw -INFILE=cluster9size16.txt -TYPE=protein 
clustalw -INFILE=cluster66size5.txt -TYPE=protein 
clustalw -INFILE=cluster3size26.txt -TYPE=protein 
clustalw -INFILE=cluster65size5.txt -TYPE=protein 
clustalw -INFILE=cluster43size7.txt -TYPE=protein 
clustalw -INFILE=cluster67size5.txt -TYPE=protein 
clustalw -INFILE=cluster53size6.txt -TYPE=protein 
clustalw -INFILE=cluster45size7.txt -TYPE=protein 
clustalw -INFILE=cluster23size9.txt -TYPE=protein 
clustalw -INFILE=cluster36size7.txt -TYPE=protein 
clustalw -INFILE=cluster30size8.txt -TYPE=protein 
clustalw -INFILE=cluster75size5.txt -TYPE=protein 
clustalw -INFILE=cluster22size9.txt -TYPE=protein 
clustalw -INFILE=cluster58size6.txt -TYPE=protein 
clustalw -INFILE=cluster10size15.txt -TYPE=protein 
clustalw -INFILE=cluster1size44.txt -TYPE=protein 
clustalw -INFILE=cluster68size5.txt -TYPE=protein 
clustalw -INFILE=cluster57size6.txt -TYPE=protein 
clustalw -INFILE=cluster61size5.txt -TYPE=protein 
clustalw -INFILE=cluster26size8.txt -TYPE=protein 
clustalw -INFILE=cluster37size7.txt -TYPE=protein 
clustalw -INFILE=cluster12size13.txt -TYPE=protein 
clustalw -INFILE=cluster64size5.txt -TYPE=protein 
clustalw -INFILE=cluster72size5.txt -TYPE=protein 
clustalw -INFILE=cluster34size7.txt -TYPE=protein 
clustalw -INFILE=cluster38size7.txt -TYPE=protein 
clustalw -INFILE=cluster71size5.txt -TYPE=protein 
clustalw -INFILE=cluster79size5.txt -TYPE=protein 
clustalw -INFILE=cluster60size6.txt -TYPE=protein 
clustalw -INFILE=cluster73size5.txt -TYPE=protein 
clustalw -INFILE=cluster14size11.txt -TYPE=protein 
clustalw -INFILE=cluster39size7.txt -TYPE=protein 
clustalw -INFILE=cluster51size6.txt -TYPE=protein 
clustalw -INFILE=cluster69size5.txt -TYPE=protein 
clustalw -INFILE=cluster5size20.txt -TYPE=protein 
clustalw -INFILE=cluster24size9.txt -TYPE=protein 
clustalw -INFILE=cluster21size10.txt -TYPE=protein 
clustalw -INFILE=cluster8size17.txt -TYPE=protein 
clustalw -INFILE=cluster11size14.txt -TYPE=protein 
