python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster10size8.txt -o ./AQ/cluster10size8.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster10size8.txt.aln -o ./AQ/cluster10size8.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster10size8.txt.aln.seq -o ./AQ/cluster10size8.txt.aln.seq.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster11size8.txt -o ./AQ/cluster11size8.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster11size8.txt.aln -o ./AQ/cluster11size8.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster12size7.txt -o ./AQ/cluster12size7.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster12size7.txt.aln -o ./AQ/cluster12size7.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster13size7.txt -o ./AQ/cluster13size7.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster13size7.txt.aln -o ./AQ/cluster13size7.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster14size6.txt -o ./AQ/cluster14size6.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster14size6.txt.aln -o ./AQ/cluster14size6.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster15size6.txt -o ./AQ/cluster15size6.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster15size6.txt.aln -o ./AQ/cluster15size6.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster16size6.txt -o ./AQ/cluster16size6.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster16size6.txt.aln -o ./AQ/cluster16size6.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster17size6.txt -o ./AQ/cluster17size6.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster17size6.txt.aln -o ./AQ/cluster17size6.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster18size5.txt -o ./AQ/cluster18size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster18size5.txt.aln -o ./AQ/cluster18size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster19size5.txt -o ./AQ/cluster19size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster19size5.txt.aln -o ./AQ/cluster19size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster1size13.txt -o ./AQ/cluster1size13.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster1size13.txt.aln -o ./AQ/cluster1size13.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster20size5.txt -o ./AQ/cluster20size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster20size5.txt.aln -o ./AQ/cluster20size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster21size5.txt -o ./AQ/cluster21size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster21size5.txt.aln -o ./AQ/cluster21size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster22size5.txt -o ./AQ/cluster22size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster22size5.txt.aln -o ./AQ/cluster22size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster2size13.txt -o ./AQ/cluster2size13.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster2size13.txt.aln -o ./AQ/cluster2size13.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster3size12.txt -o ./AQ/cluster3size12.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster3size12.txt.aln -o ./AQ/cluster3size12.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster4size12.txt -o ./AQ/cluster4size12.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster4size12.txt.aln -o ./AQ/cluster4size12.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster5size12.txt -o ./AQ/cluster5size12.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster5size12.txt.aln -o ./AQ/cluster5size12.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster6size11.txt -o ./AQ/cluster6size11.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster6size11.txt.aln -o ./AQ/cluster6size11.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster7size11.txt -o ./AQ/cluster7size11.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster7size11.txt.aln -o ./AQ/cluster7size11.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster8size10.txt -o ./AQ/cluster8size10.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster8size10.txt.aln -o ./AQ/cluster8size10.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster9size9.txt -o ./AQ/cluster9size9.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./AQ/cluster9size9.txt.aln -o ./AQ/cluster9size9.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster10size15.txt -o ./SC/cluster10size15.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster10size15.txt.aln -o ./SC/cluster10size15.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster11size14.txt -o ./SC/cluster11size14.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster11size14.txt.aln -o ./SC/cluster11size14.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster12size13.txt -o ./SC/cluster12size13.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster12size13.txt.aln -o ./SC/cluster12size13.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster13size11.txt -o ./SC/cluster13size11.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster13size11.txt.aln -o ./SC/cluster13size11.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster14size11.txt -o ./SC/cluster14size11.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster14size11.txt.aln -o ./SC/cluster14size11.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster15size11.txt -o ./SC/cluster15size11.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster15size11.txt.aln -o ./SC/cluster15size11.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster16size11.txt -o ./SC/cluster16size11.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster16size11.txt.aln -o ./SC/cluster16size11.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster17size10.txt -o ./SC/cluster17size10.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster17size10.txt.aln -o ./SC/cluster17size10.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster18size10.txt -o ./SC/cluster18size10.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster18size10.txt.aln -o ./SC/cluster18size10.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster19size10.txt -o ./SC/cluster19size10.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster19size10.txt.aln -o ./SC/cluster19size10.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster1size44.txt -o ./SC/cluster1size44.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster1size44.txt.aln -o ./SC/cluster1size44.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster20size10.txt -o ./SC/cluster20size10.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster20size10.txt.aln -o ./SC/cluster20size10.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster21size10.txt -o ./SC/cluster21size10.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster21size10.txt.aln -o ./SC/cluster21size10.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster22size9.txt -o ./SC/cluster22size9.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster22size9.txt.aln -o ./SC/cluster22size9.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster23size9.txt -o ./SC/cluster23size9.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster23size9.txt.aln -o ./SC/cluster23size9.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster24size9.txt -o ./SC/cluster24size9.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster24size9.txt.aln -o ./SC/cluster24size9.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster25size9.txt -o ./SC/cluster25size9.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster25size9.txt.aln -o ./SC/cluster25size9.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster26size8.txt -o ./SC/cluster26size8.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster26size8.txt.aln -o ./SC/cluster26size8.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster27size8.txt -o ./SC/cluster27size8.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster27size8.txt.aln -o ./SC/cluster27size8.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster28size8.txt -o ./SC/cluster28size8.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster28size8.txt.aln -o ./SC/cluster28size8.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster29size8.txt -o ./SC/cluster29size8.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster29size8.txt.aln -o ./SC/cluster29size8.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster2size30.txt -o ./SC/cluster2size30.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster2size30.txt.aln -o ./SC/cluster2size30.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster30size8.txt -o ./SC/cluster30size8.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster30size8.txt.aln -o ./SC/cluster30size8.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster31size8.txt -o ./SC/cluster31size8.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster31size8.txt.aln -o ./SC/cluster31size8.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster32size8.txt -o ./SC/cluster32size8.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster32size8.txt.aln -o ./SC/cluster32size8.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster33size8.txt -o ./SC/cluster33size8.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster33size8.txt.aln -o ./SC/cluster33size8.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster34size7.txt -o ./SC/cluster34size7.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster34size7.txt.aln -o ./SC/cluster34size7.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster35size7.txt -o ./SC/cluster35size7.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster35size7.txt.aln -o ./SC/cluster35size7.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster36size7.txt -o ./SC/cluster36size7.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster36size7.txt.aln -o ./SC/cluster36size7.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster37size7.txt -o ./SC/cluster37size7.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster37size7.txt.aln -o ./SC/cluster37size7.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster38size7.txt -o ./SC/cluster38size7.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster38size7.txt.aln -o ./SC/cluster38size7.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster39size7.txt -o ./SC/cluster39size7.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster39size7.txt.aln -o ./SC/cluster39size7.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster3size26.txt -o ./SC/cluster3size26.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster3size26.txt.aln -o ./SC/cluster3size26.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster40size7.txt -o ./SC/cluster40size7.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster40size7.txt.aln -o ./SC/cluster40size7.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster41size7.txt -o ./SC/cluster41size7.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster41size7.txt.aln -o ./SC/cluster41size7.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster42size7.txt -o ./SC/cluster42size7.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster42size7.txt.aln -o ./SC/cluster42size7.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster43size7.txt -o ./SC/cluster43size7.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster43size7.txt.aln -o ./SC/cluster43size7.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster44size7.txt -o ./SC/cluster44size7.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster44size7.txt.aln -o ./SC/cluster44size7.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster45size7.txt -o ./SC/cluster45size7.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster45size7.txt.aln -o ./SC/cluster45size7.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster46size7.txt -o ./SC/cluster46size7.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster46size7.txt.aln -o ./SC/cluster46size7.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster47size7.txt -o ./SC/cluster47size7.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster47size7.txt.aln -o ./SC/cluster47size7.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster48size7.txt -o ./SC/cluster48size7.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster48size7.txt.aln -o ./SC/cluster48size7.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster49size7.txt -o ./SC/cluster49size7.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster49size7.txt.aln -o ./SC/cluster49size7.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster4size23.txt -o ./SC/cluster4size23.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster4size23.txt.aln -o ./SC/cluster4size23.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster50size6.txt -o ./SC/cluster50size6.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster50size6.txt.aln -o ./SC/cluster50size6.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster51size6.txt -o ./SC/cluster51size6.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster51size6.txt.aln -o ./SC/cluster51size6.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster52size6.txt -o ./SC/cluster52size6.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster52size6.txt.aln -o ./SC/cluster52size6.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster53size6.txt -o ./SC/cluster53size6.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster53size6.txt.aln -o ./SC/cluster53size6.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster54size6.txt -o ./SC/cluster54size6.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster54size6.txt.aln -o ./SC/cluster54size6.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster55size6.txt -o ./SC/cluster55size6.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster55size6.txt.aln -o ./SC/cluster55size6.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster56size6.txt -o ./SC/cluster56size6.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster56size6.txt.aln -o ./SC/cluster56size6.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster57size6.txt -o ./SC/cluster57size6.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster57size6.txt.aln -o ./SC/cluster57size6.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster58size6.txt -o ./SC/cluster58size6.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster58size6.txt.aln -o ./SC/cluster58size6.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster59size6.txt -o ./SC/cluster59size6.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster59size6.txt.aln -o ./SC/cluster59size6.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster5size20.txt -o ./SC/cluster5size20.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster5size20.txt.aln -o ./SC/cluster5size20.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster60size6.txt -o ./SC/cluster60size6.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster60size6.txt.aln -o ./SC/cluster60size6.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster61size5.txt -o ./SC/cluster61size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster61size5.txt.aln -o ./SC/cluster61size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster62size5.txt -o ./SC/cluster62size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster62size5.txt.aln -o ./SC/cluster62size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster63size5.txt -o ./SC/cluster63size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster63size5.txt.aln -o ./SC/cluster63size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster64size5.txt -o ./SC/cluster64size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster64size5.txt.aln -o ./SC/cluster64size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster65size5.txt -o ./SC/cluster65size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster65size5.txt.aln -o ./SC/cluster65size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster66size5.txt -o ./SC/cluster66size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster66size5.txt.aln -o ./SC/cluster66size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster67size5.txt -o ./SC/cluster67size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster67size5.txt.aln -o ./SC/cluster67size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster68size5.txt -o ./SC/cluster68size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster68size5.txt.aln -o ./SC/cluster68size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster69size5.txt -o ./SC/cluster69size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster69size5.txt.aln -o ./SC/cluster69size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster6size19.txt -o ./SC/cluster6size19.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster6size19.txt.aln -o ./SC/cluster6size19.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster70size5.txt -o ./SC/cluster70size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster70size5.txt.aln -o ./SC/cluster70size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster71size5.txt -o ./SC/cluster71size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster71size5.txt.aln -o ./SC/cluster71size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster72size5.txt -o ./SC/cluster72size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster72size5.txt.aln -o ./SC/cluster72size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster73size5.txt -o ./SC/cluster73size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster73size5.txt.aln -o ./SC/cluster73size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster74size5.txt -o ./SC/cluster74size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster74size5.txt.aln -o ./SC/cluster74size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster75size5.txt -o ./SC/cluster75size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster75size5.txt.aln -o ./SC/cluster75size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster76size5.txt -o ./SC/cluster76size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster76size5.txt.aln -o ./SC/cluster76size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster77size5.txt -o ./SC/cluster77size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster77size5.txt.aln -o ./SC/cluster77size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster78size5.txt -o ./SC/cluster78size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster78size5.txt.aln -o ./SC/cluster78size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster79size5.txt -o ./SC/cluster79size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster79size5.txt.aln -o ./SC/cluster79size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster7size18.txt -o ./SC/cluster7size18.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster7size18.txt.aln -o ./SC/cluster7size18.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster80size5.txt -o ./SC/cluster80size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster80size5.txt.aln -o ./SC/cluster80size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster81size5.txt -o ./SC/cluster81size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster81size5.txt.aln -o ./SC/cluster81size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster8size17.txt -o ./SC/cluster8size17.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster8size17.txt.aln -o ./SC/cluster8size17.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster9size16.txt -o ./SC/cluster9size16.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./SC/cluster9size16.txt.aln -o ./SC/cluster9size16.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./XT/cluster10size5.txt -o ./XT/cluster10size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./XT/cluster10size5.txt.aln -o ./XT/cluster10size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./XT/cluster1size14.txt -o ./XT/cluster1size14.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./XT/cluster1size14.txt.aln -o ./XT/cluster1size14.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./XT/cluster2size10.txt -o ./XT/cluster2size10.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./XT/cluster2size10.txt.aln -o ./XT/cluster2size10.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./XT/cluster3size7.txt -o ./XT/cluster3size7.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./XT/cluster3size7.txt.aln -o ./XT/cluster3size7.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./XT/cluster4size7.txt -o ./XT/cluster4size7.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./XT/cluster4size7.txt.aln -o ./XT/cluster4size7.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./XT/cluster5size6.txt -o ./XT/cluster5size6.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./XT/cluster5size6.txt.aln -o ./XT/cluster5size6.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./XT/cluster6size6.txt -o ./XT/cluster6size6.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./XT/cluster6size6.txt.aln -o ./XT/cluster6size6.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./XT/cluster7size5.txt -o ./XT/cluster7size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./XT/cluster7size5.txt.aln -o ./XT/cluster7size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./XT/cluster8size5.txt -o ./XT/cluster8size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./XT/cluster8size5.txt.aln -o ./XT/cluster8size5.txt.aln.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./XT/cluster9size5.txt -o ./XT/cluster9size5.txt.seq
python ../0_bin/python_script/1_consensus_seq.py -i ./XT/cluster9size5.txt.aln -o ./XT/cluster9size5.txt.aln.seq
