probcons -clustalw ./AQ/cluster10size8.txt > ./AQ/cluster10size8.txt.aln
probcons -clustalw ./AQ/cluster11size8.txt > ./AQ/cluster11size8.txt.aln
probcons -clustalw ./AQ/cluster12size7.txt > ./AQ/cluster12size7.txt.aln
probcons -clustalw ./AQ/cluster13size7.txt > ./AQ/cluster13size7.txt.aln
probcons -clustalw ./AQ/cluster14size6.txt > ./AQ/cluster14size6.txt.aln
probcons -clustalw ./AQ/cluster15size6.txt > ./AQ/cluster15size6.txt.aln
probcons -clustalw ./AQ/cluster16size6.txt > ./AQ/cluster16size6.txt.aln
probcons -clustalw ./AQ/cluster17size6.txt > ./AQ/cluster17size6.txt.aln
probcons -clustalw ./AQ/cluster18size5.txt > ./AQ/cluster18size5.txt.aln
probcons -clustalw ./AQ/cluster19size5.txt > ./AQ/cluster19size5.txt.aln
probcons -clustalw ./AQ/cluster1size13.txt > ./AQ/cluster1size13.txt.aln
probcons -clustalw ./AQ/cluster20size5.txt > ./AQ/cluster20size5.txt.aln
probcons -clustalw ./AQ/cluster21size5.txt > ./AQ/cluster21size5.txt.aln
probcons -clustalw ./AQ/cluster22size5.txt > ./AQ/cluster22size5.txt.aln
probcons -clustalw ./AQ/cluster2size13.txt > ./AQ/cluster2size13.txt.aln
probcons -clustalw ./AQ/cluster3size12.txt > ./AQ/cluster3size12.txt.aln
probcons -clustalw ./AQ/cluster4size12.txt > ./AQ/cluster4size12.txt.aln
probcons -clustalw ./AQ/cluster5size12.txt > ./AQ/cluster5size12.txt.aln
probcons -clustalw ./AQ/cluster6size11.txt > ./AQ/cluster6size11.txt.aln
probcons -clustalw ./AQ/cluster7size11.txt > ./AQ/cluster7size11.txt.aln
probcons -clustalw ./AQ/cluster8size10.txt > ./AQ/cluster8size10.txt.aln
probcons -clustalw ./AQ/cluster9size9.txt > ./AQ/cluster9size9.txt.aln
probcons -clustalw ./SC/cluster10size15.txt > ./SC/cluster10size15.txt.aln
probcons -clustalw ./SC/cluster11size14.txt > ./SC/cluster11size14.txt.aln
probcons -clustalw ./SC/cluster12size13.txt > ./SC/cluster12size13.txt.aln
probcons -clustalw ./SC/cluster13size11.txt > ./SC/cluster13size11.txt.aln
probcons -clustalw ./SC/cluster14size11.txt > ./SC/cluster14size11.txt.aln
probcons -clustalw ./SC/cluster15size11.txt > ./SC/cluster15size11.txt.aln
probcons -clustalw ./SC/cluster16size11.txt > ./SC/cluster16size11.txt.aln
probcons -clustalw ./SC/cluster17size10.txt > ./SC/cluster17size10.txt.aln
probcons -clustalw ./SC/cluster18size10.txt > ./SC/cluster18size10.txt.aln
probcons -clustalw ./SC/cluster19size10.txt > ./SC/cluster19size10.txt.aln
probcons -clustalw ./SC/cluster1size44.txt > ./SC/cluster1size44.txt.aln
probcons -clustalw ./SC/cluster20size10.txt > ./SC/cluster20size10.txt.aln
probcons -clustalw ./SC/cluster21size10.txt > ./SC/cluster21size10.txt.aln
probcons -clustalw ./SC/cluster22size9.txt > ./SC/cluster22size9.txt.aln
probcons -clustalw ./SC/cluster23size9.txt > ./SC/cluster23size9.txt.aln
probcons -clustalw ./SC/cluster24size9.txt > ./SC/cluster24size9.txt.aln
probcons -clustalw ./SC/cluster25size9.txt > ./SC/cluster25size9.txt.aln
probcons -clustalw ./SC/cluster26size8.txt > ./SC/cluster26size8.txt.aln
probcons -clustalw ./SC/cluster27size8.txt > ./SC/cluster27size8.txt.aln
probcons -clustalw ./SC/cluster28size8.txt > ./SC/cluster28size8.txt.aln
probcons -clustalw ./SC/cluster29size8.txt > ./SC/cluster29size8.txt.aln
probcons -clustalw ./SC/cluster2size30.txt > ./SC/cluster2size30.txt.aln
probcons -clustalw ./SC/cluster30size8.txt > ./SC/cluster30size8.txt.aln
probcons -clustalw ./SC/cluster31size8.txt > ./SC/cluster31size8.txt.aln
probcons -clustalw ./SC/cluster32size8.txt > ./SC/cluster32size8.txt.aln
probcons -clustalw ./SC/cluster33size8.txt > ./SC/cluster33size8.txt.aln
probcons -clustalw ./SC/cluster34size7.txt > ./SC/cluster34size7.txt.aln
probcons -clustalw ./SC/cluster35size7.txt > ./SC/cluster35size7.txt.aln
probcons -clustalw ./SC/cluster36size7.txt > ./SC/cluster36size7.txt.aln
probcons -clustalw ./SC/cluster37size7.txt > ./SC/cluster37size7.txt.aln
probcons -clustalw ./SC/cluster38size7.txt > ./SC/cluster38size7.txt.aln
probcons -clustalw ./SC/cluster39size7.txt > ./SC/cluster39size7.txt.aln
probcons -clustalw ./SC/cluster3size26.txt > ./SC/cluster3size26.txt.aln
probcons -clustalw ./SC/cluster40size7.txt > ./SC/cluster40size7.txt.aln
probcons -clustalw ./SC/cluster41size7.txt > ./SC/cluster41size7.txt.aln
probcons -clustalw ./SC/cluster42size7.txt > ./SC/cluster42size7.txt.aln
probcons -clustalw ./SC/cluster43size7.txt > ./SC/cluster43size7.txt.aln
probcons -clustalw ./SC/cluster44size7.txt > ./SC/cluster44size7.txt.aln
probcons -clustalw ./SC/cluster45size7.txt > ./SC/cluster45size7.txt.aln
probcons -clustalw ./SC/cluster46size7.txt > ./SC/cluster46size7.txt.aln
probcons -clustalw ./SC/cluster47size7.txt > ./SC/cluster47size7.txt.aln
probcons -clustalw ./SC/cluster48size7.txt > ./SC/cluster48size7.txt.aln
probcons -clustalw ./SC/cluster49size7.txt > ./SC/cluster49size7.txt.aln
probcons -clustalw ./SC/cluster4size23.txt > ./SC/cluster4size23.txt.aln
probcons -clustalw ./SC/cluster50size6.txt > ./SC/cluster50size6.txt.aln
probcons -clustalw ./SC/cluster51size6.txt > ./SC/cluster51size6.txt.aln
probcons -clustalw ./SC/cluster52size6.txt > ./SC/cluster52size6.txt.aln
probcons -clustalw ./SC/cluster53size6.txt > ./SC/cluster53size6.txt.aln
probcons -clustalw ./SC/cluster54size6.txt > ./SC/cluster54size6.txt.aln
probcons -clustalw ./SC/cluster55size6.txt > ./SC/cluster55size6.txt.aln
probcons -clustalw ./SC/cluster56size6.txt > ./SC/cluster56size6.txt.aln
probcons -clustalw ./SC/cluster57size6.txt > ./SC/cluster57size6.txt.aln
probcons -clustalw ./SC/cluster58size6.txt > ./SC/cluster58size6.txt.aln
probcons -clustalw ./SC/cluster59size6.txt > ./SC/cluster59size6.txt.aln
probcons -clustalw ./SC/cluster5size20.txt > ./SC/cluster5size20.txt.aln
probcons -clustalw ./SC/cluster60size6.txt > ./SC/cluster60size6.txt.aln
probcons -clustalw ./SC/cluster61size5.txt > ./SC/cluster61size5.txt.aln
probcons -clustalw ./SC/cluster62size5.txt > ./SC/cluster62size5.txt.aln
probcons -clustalw ./SC/cluster63size5.txt > ./SC/cluster63size5.txt.aln
probcons -clustalw ./SC/cluster64size5.txt > ./SC/cluster64size5.txt.aln
probcons -clustalw ./SC/cluster65size5.txt > ./SC/cluster65size5.txt.aln
probcons -clustalw ./SC/cluster66size5.txt > ./SC/cluster66size5.txt.aln
probcons -clustalw ./SC/cluster67size5.txt > ./SC/cluster67size5.txt.aln
probcons -clustalw ./SC/cluster68size5.txt > ./SC/cluster68size5.txt.aln
probcons -clustalw ./SC/cluster69size5.txt > ./SC/cluster69size5.txt.aln
probcons -clustalw ./SC/cluster6size19.txt > ./SC/cluster6size19.txt.aln
probcons -clustalw ./SC/cluster70size5.txt > ./SC/cluster70size5.txt.aln
probcons -clustalw ./SC/cluster71size5.txt > ./SC/cluster71size5.txt.aln
probcons -clustalw ./SC/cluster72size5.txt > ./SC/cluster72size5.txt.aln
probcons -clustalw ./SC/cluster73size5.txt > ./SC/cluster73size5.txt.aln
probcons -clustalw ./SC/cluster74size5.txt > ./SC/cluster74size5.txt.aln
probcons -clustalw ./SC/cluster75size5.txt > ./SC/cluster75size5.txt.aln
probcons -clustalw ./SC/cluster76size5.txt > ./SC/cluster76size5.txt.aln
probcons -clustalw ./SC/cluster77size5.txt > ./SC/cluster77size5.txt.aln
probcons -clustalw ./SC/cluster78size5.txt > ./SC/cluster78size5.txt.aln
probcons -clustalw ./SC/cluster79size5.txt > ./SC/cluster79size5.txt.aln
probcons -clustalw ./SC/cluster7size18.txt > ./SC/cluster7size18.txt.aln
probcons -clustalw ./SC/cluster80size5.txt > ./SC/cluster80size5.txt.aln
probcons -clustalw ./SC/cluster81size5.txt > ./SC/cluster81size5.txt.aln
probcons -clustalw ./SC/cluster8size17.txt > ./SC/cluster8size17.txt.aln
probcons -clustalw ./SC/cluster9size16.txt > ./SC/cluster9size16.txt.aln
probcons -clustalw ./XT/cluster10size5.txt > ./XT/cluster10size5.txt.aln
probcons -clustalw ./XT/cluster1size14.txt > ./XT/cluster1size14.txt.aln
probcons -clustalw ./XT/cluster2size10.txt > ./XT/cluster2size10.txt.aln
probcons -clustalw ./XT/cluster3size7.txt > ./XT/cluster3size7.txt.aln
probcons -clustalw ./XT/cluster4size7.txt > ./XT/cluster4size7.txt.aln
probcons -clustalw ./XT/cluster5size6.txt > ./XT/cluster5size6.txt.aln
probcons -clustalw ./XT/cluster6size6.txt > ./XT/cluster6size6.txt.aln
probcons -clustalw ./XT/cluster7size5.txt > ./XT/cluster7size5.txt.aln
probcons -clustalw ./XT/cluster8size5.txt > ./XT/cluster8size5.txt.aln
probcons -clustalw ./XT/cluster9size5.txt > ./XT/cluster9size5.txt.aln
