#perl  ./combineColumn.pl -f1 /home/xux/Projects/SECOM/SECOM/Sponge/XT_proteins_ltAED075_E/seed6/pfam.tsv -f2 /home/xux/Projects/SECOM/SECOM/Sponge/XT_proteins_ltAED075_E/seed6/AQ_blast.tsv -k 1 -c2 2 -out /home/xux/Projects/SECOM/SECOM/Sponge/XT_proteins_ltAED075_E/seed6/pfam_AQ.tsv && \
#perl  ./combineColumn.pl -f1 /home/xux/Projects/SECOM/SECOM/Sponge/XT_proteins_ltAED075_E/seed6/pfam_AQ.tsv -f2 /home/xux/Projects/SECOM/SECOM/Sponge/XT_proteins_ltAED075_E/seed6/SC_blast.tsv -k 1 -c2 2 -out /home/xux/Projects/SECOM/SECOM/Sponge/XT_proteins_ltAED075_E/seed6/pfam_AQ_SC.tsv && \
#perl  ./combineColumn.pl -f1 /home/xux/Projects/SECOM/SECOM/Sponge/XT_proteins_ltAED075_E/seed6/pfam_AQ_SC.tsv -f2 /home/xux/Projects/SECOM/SECOM/Sponge/XT_proteins_ltAED075_E/seed6/nr_blast.tsv -k 1 -c2 2 -out /home/xux/Projects/SECOM/SECOM/Sponge/XT_proteins_ltAED075_E/seed6/pfam_AQ_SC_nr.tsv && \
#rm /home/xux/Projects/SECOM/SECOM/Sponge/XT_proteins_ltAED075_E/seed6/pfam_AQ.tsv /home/xux/Projects/SECOM/SECOM/Sponge/XT_proteins_ltAED075_E/seed6/pfam_AQ_SC.tsv 

perl  ./combineColumn.pl -f1 /home/xux/Projects/SECOM/SECOM/Sponge/Sc_ltAED075_E/seed6/pfam.tsv -f2 /home/xux/Projects/SECOM/SECOM/Sponge/Sc_ltAED075_E/seed6/AQ_blast.tsv -k 1 -c2 2 -out /home/xux/Projects/SECOM/SECOM/Sponge/Sc_ltAED075_E/seed6/pfam_AQ.tsv && \
perl  ./combineColumn.pl -f1 /home/xux/Projects/SECOM/SECOM/Sponge/Sc_ltAED075_E/seed6/pfam_AQ.tsv -f2 /home/xux/Projects/SECOM/SECOM/Sponge/Sc_ltAED075_E/seed6/XT_blast.tsv -k 1 -c2 2 -out /home/xux/Projects/SECOM/SECOM/Sponge/Sc_ltAED075_E/seed6/pfam_AQ_XT.tsv && \
perl  ./combineColumn.pl -f1 /home/xux/Projects/SECOM/SECOM/Sponge/Sc_ltAED075_E/seed6/pfam_AQ_XT.tsv -f2 /home/xux/Projects/SECOM/SECOM/Sponge/Sc_ltAED075_E/seed6/nr_blast.tsv -k 1 -c2 2 -out /home/xux/Projects/SECOM/SECOM/Sponge/Sc_ltAED075_E/seed6/pfam_AQ_XT_nr.tsv && \
rm /home/xux/Projects/SECOM/SECOM/Sponge/Sc_ltAED075_E/seed6/pfam_AQ.tsv /home/xux/Projects/SECOM/SECOM/Sponge/Sc_ltAED075_E/seed6/pfam_AQ_XT.tsv 
